version: "3.4"

services:
  image: nginx-core # Our custom NGINX Docker image  
    container_name: "nginxcore" # Name the service  
    ports:
      - "8080:80"
  ConsoleBackend:
    image: ksups111/botapi:dev1.9
    ports:
      - "5003:5004"
    build:
      context: .
      dockerfile: Dockerfile.web

  WebFrontend:
    image: ksups111/dash:dev1.1
    ports:
      - "5001:5002"
    build:
      context: .
      dockerfile: Dockerfile.con
