#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build

WORKDIR /src
COPY ./DiscordBotProject/BotDash/BotDash.csproj DiscordBotProject/BotDash/

RUN dotnet restore DiscordBotProject/BotDash/BotDash.csproj
COPY . .
WORKDIR /src/DiscordBotProject/BotDash
RUN dotnet build "BotDash.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "BotDash.csproj" -c Release -o /publish

# new
FROM nginx:alpine AS final
WORKDIR /usr/share/nginx/html

COPY --from=publish /publish/wwwroot /usr/local/webapp/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf

# old

#FROM base AS final
#WORKDIR /app
#COPY --from=publish /app .
#ENTRYPOINT ["dotnet", "BotDash.dll"]