import ruamel.yaml

yaml_str = """\
version: "3.4"
services:
  Nginx:
    image: nginx
      container_name: "nginxcore"
      ports:
        - "8080:80"
    networks:  
      - mynetwork
  ConsoleBackend:
    image: ksups111/botapi:dev1.9
    ports:
      - "5003:80"
    build:
      context: .
      dockerfile: Dockerfile.web
    networks:  
      - mynetwork

  WebFrontend:
    image: ksups111/dash:dev1.1
    ports:
      - "5001:80"
    build:
      context: .
      dockerfile: Dockerfile.con
    networks:  
      - mynetwork  
"""

#networks:  
#  mynetwork:
#    driver: bridge

data = ruamel.yaml.round_trip_load(yaml_str)
print(ruamel.yaml.round_trip_dump(data))